version: "3.7"
services:
  postgres:
    image: postgres:alpine
    volumes:
      - ./postgres/schema/create.sql:/docker-entrypoint-initdb.d/create.sql
    restart: always
    env_file:
      - ./postgres/.env
    ports:
      - "5432:5432"
  bell-server:
    build:
      context: ./bell
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - "8003:8003"
  audio-storage:
    build:
      context: ./audio-storage
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "8004:8004"
  trans-service:
    build:
      context: ./Transcription
      dockerfile: ./Transcription/Dockerfile
    networks:
      - default
    depends_on:
      - whisper
    ports:
      - "8002:8002"
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "8000:8000"
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper