app:
  name: "bell-service"
http:
  port: 8003
  read_timeout: 1m
  write_timeout: 1m
  shutdown_timeout: 5s
pg:
  conn_uri: "postgres://green:0010@postgres:5432/pg-bells"
api:
  url_api: "http://hackathon.ambity.ru/api/contact"